name: PowerShell Script Trigger

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  update:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
          
    - name: Install PowerShell
      uses: microsoft/setup-powershell@v1
      
    - name: Update JSON file
      run: |
        $jsonPath = "github-learn-actions/manifest.json"
        $json = Get-Content $jsonPath -Raw | ConvertFrom-Json
        $versionParts = $json.version -split '\.'
        $versionParts[-1] = [int]$versionParts[-1] + 1
        $newVersion = $versionParts -join '.'
        $json.version = $newVersion
       
        $json | ConvertTo-Json -Depth 20 | Set-Content $jsonPath
        git config --global user.email "mpawankumarreddy6@gmail.com.com"
        git config --global user.name "Pawan"
        git add $jsonPath
        git commit -m "Update JSON file"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
