name: Update JSON file

on:
  push:
    branches:
      - main

jobs:
  update_json:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update JSON file
        run: |
          $repoPath = "$env:GITHUB_WORKSPACE"
          echo $repoPath
          $jsonPath = Join-Path $repoPath "\manifest.json"

          # Load the JSON file
          $json = Get-Content $jsonPath -Raw | ConvertFrom-Json

          # Update the property value
          $json.property = "new value"

          # Save the updated JSON object back to the file
          $json | ConvertTo-Json -Depth 4 | Set-Content $jsonPath

          # Configure Git user info
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

          # Add, commit, and push the changes
          git add $jsonPath
          git commit -m "Update JSON file"
          git push origin main
